// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv1x8ofNyeBzH2OVyj_Bxo1NpMcu3dY9w',
    appId: '1:577885081513:web:664e900f06554214bbbeb8',
    messagingSenderId: '577885081513',
    projectId: 'mysticmall',
    authDomain: 'mysticmall.firebaseapp.com',
    storageBucket: 'mysticmall.appspot.com',
    measurementId: 'G-06155YVV52',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7O5DUeqxQ7FgTc49cIvA1a4IOIIKohJs',
    appId: '1:577885081513:android:f10586bdd34760d6bbbeb8',
    messagingSenderId: '577885081513',
    projectId: 'mysticmall',
    storageBucket: 'mysticmall.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdk20ZOSfklqOIJgvl3pgeojjeXK93ayE',
    appId: '1:577885081513:ios:942c0813a94047fcbbbeb8',
    messagingSenderId: '577885081513',
    projectId: 'mysticmall',
    storageBucket: 'mysticmall.appspot.com',
    iosBundleId: 'com.example.mysticMall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdk20ZOSfklqOIJgvl3pgeojjeXK93ayE',
    appId: '1:577885081513:ios:85f767ea4ba5eaddbbbeb8',
    messagingSenderId: '577885081513',
    projectId: 'mysticmall',
    storageBucket: 'mysticmall.appspot.com',
    iosBundleId: 'com.example.mysticMall.RunnerTests',
  );
}
